### PR TITLE
Fix 34 - Rename load_taskgraph(), save_taskgraph(), and viz_graph() methods. Add draw() method

### PR DESCRIPTION
**Pull request by miguelusque**
Hi!

This PR fixes https://github.com/rapidsai/gQuant/issues/34.

`load_taskgraph()` method has been renamed to `load()`
`save_taskgraph()` method has been renamed to `save()`
`viz_graph ()` method has been renamed to `to_nxgraph`.

`draw` method has been added.

Regards,
Miguel

### CODE REVIEW

**Comment by miguelangel** [comment]
Hi Alex,

Thank you for your comments.

In relation to warnings, I will follow the instructions described in this link:

http://code.activestate.com/recipes/391367-deprecated/

Regards,
Miguel

**Comment by avolkov1** [comment]
> Hi @avolkov1 ,
> 
> Thank you for your comments.
> 
> In relation to warnings, I will follow the instructions described in this link:
> 
> http://code.activestate.com/recipes/391367-deprecated/
> 
> Regards,
> Miguel

Using a decorator is a good idea. Just put some gquant unique string in the beginning of the warning message such as "gquant API change". I want to be able to inhibit warnings via this syntax:
```
warnings.filterwarnings('ignore', message='gquant API change')
```

**Comment by miguelangel** [comment]
Hi again,

I think that I won't finally follow my own comment. That way, I will be able to add custom deprecation messages.

And sure! I will add `gQuant API change` at the beginning of the warning message.

**Comment by avolkov1** [comment]
Also, make sure to inform the caller of the new API. Parameterize the decorator. Something like this:
```
def deprecated_api(new_func_name):
    def deprecated(func):
        """This is a decorator which can be used to mark functions
        as deprecated. It will result in a warning being emmitted
        when the function is used."""
        def newFunc(*args, **kwargs):
            warnings.warn(
                "gquant API change: Call to deprecated function {}. Replace with {}"
                .format(func.__name__, new_func_name),
                category=DeprecationWarning)
            return func(*args, **kwargs)

        newFunc.__name__ = func.__name__
        newFunc.__doc__ = func.__doc__
        newFunc.__dict__.update(func.__dict__)
        return newFunc

    return deprecated
    



# === Examples of use ===

@deprecated_api("some_new_function")
def some_old_function(x,y):
    return x + y

```

**Comment by miguelangel** [comment]
Ok! I'll do as suggested.

**Comment by yidong72** [comment]
close this

**Pull request closed without merging**
