### PR TITLE
Fix 17 - cuIndicator notebook plot widget is too complicated (WIP)

### PR DESCRIPTION
**Pull request by miguelangel**
Hi,

This is a WIP of issue https://github.com/rapidsai/gQuant/issues/17.

It is not finished, but it is much better than the existing example in `master` branch.

It is also needed because it makes use of `TaskGraph` and `TaskSpecSchema` classes.

Therefore, I would like it to be merged into master this week, and I will continue polishing it in the next few days.

Regards,
Miguel

P.S.: Final refactoring is subject to change significantly. I am still designing the final solution.

### CODE REVIEW

**Comment by avolkov1** [comment]
The `create_figure` could be refactored. It looks the same. Only the label or title seems to differ.
```
# module: viz_common.py

def create_figure(title, stock, dt_scale, sc, color_id, f, indicator_figure_height, figure_width, add_new_indicator):
    sc_co = LinearScale()
    ax_y = Axis(label=title, scale=sc_co, orientation='vertical')
    new_line = Lines(x=stock.datetime, y=stock['out'], scales={'x': dt_scale, 'y': sc_co}, colors=[CATEGORY20[color_id[0]]])
    new_fig = Figure(marks=[new_line], axes=[ax_y])
    new_fig.layout.height = indicator_figure_height
    new_fig.layout.width = figure_width                    
    figs = [new_line]
    # add new figure
    add_new_indicator(new_fig)
    return figs
```

Other then `create_figure` the other functions differ so it's hard to unify them. But cell 5 is still huge. Pretty much that whole cell 5 should be in a module and imported. Refer to `plotutils.py` and `06_xgboost_trade.ipynb`. It should be like that ideally.

**Comment by miguelangel** [comment]
Hi Alex,

I will follow your comments in the next PR.

Cell #5 is still huge, but much smaller than before.

If you don’t mind, I’d like to merge this version. I am aware there is a lot of room for improvement in this notebook, but it is better than the current version in master.

I’ll try to have a definitive version of this notebook by the end of next week.

Regards,
Miguel

**Comment by avolkov1** [comment]
> Hi Alex,
> 
> I will follow your comments in the next PR.
> 
> Cell #5 is still huge, but much smaller than before.
> 
> If you don’t mind, I’d like to merge this version. I am aware there is a lot of room for improvement in this notebook, but it is better than the current version in master.
> 
> I’ll try to have a definitive version of this notebook by the end of next week.
> 
> Regards,
> Miguel

Fine by me.

**Comment by yidong72** [comment]
Fine with me too

**Comment by avolkov1** [comment]
Alright, which one of us is gonna merge this.

**Comment by yidong72** [comment]
@avolkov1, can you do it? since you do most of the review for this.

**Comment by avolkov1** [comment]
> @avolkov1, can you do it? since you do most of the review for this.

No problem. I'll merge this now then.

**Pull request merged**
