### PR TITLE
gQuant34 - Update build.sh to make use of RAPIDS v0.8 container

### PR DESCRIPTION
**Pull request by miguelangel**
Changed RAPIDS container to `cuda9.2-runtime-ubuntu16.04`.
Downgrade `jupyterlab `to `0.35.4` due to incompatibility issues with plots in `jupyterlab=1.0.4`.
Remove `source activate rapids`. Not needed anymore.

### CODE REVIEW

**Comment by miguelangel** [comment]
Thanks Yi!

I'll do for cuda 10.0 (RAPIDS v0.8 does not support 10.1 yet) 😅

**Comment by miguelangel** [comment]
What about an interactive script, where the user selects 9.2 (default) or 10.0?

**Comment by yidong72** [comment]
> What about an interactive script, where the user selects 9.2 (default) or 10.0?

The interactive script is a good idea. Maybe add in the option of using the vim jupyterlab extension.

**Comment by yidong72** [comment]
That script looks good. Could you create the PR based on the develop branch? And the process is reviewer should approve the branch and click on the "merge" button.

**Comment by avolkov1** [comment]
This should be reverted. Once PR #15 is complete and merged into develop, synchronize master with develop (make a PR to merge develop into master). Then all the latest changes will be reflected in master.

**Pull request merged**
