### PR TITLE
Merge develop to master

### PR DESCRIPTION
**Pull request by yidong72**
We have a set of good changes for gQuant. Let's review and merge it into the master branch.

### CODE REVIEW

**Comment by yidong72** [comment]
> We have a set of good changes for gQuant. Let's review and merge it into the master branch.

Maybe tag it as version 0.1.0 ? @miguelangel @avolkov1

**Comment by miguelangel** [comment]
I will submit a review of notebook 04 in the next couple of hours. Could you please wait until have it merged in develop?

**Comment by yidong72** [comment]
> I will submit a review of notebook 04 in the next couple of hours. Could you please wait until have it merged in develop?

Yes. we can wait for that.

**Comment by miguelangel** [comment]
I will also submit a new version of indicator notebook. It is a WIP, but a bit cleaner than existing.

**Comment by miguelangel** [comment]
Hi all,

I have just submitted both PR (notebook #04 and indicator_demo.ipynb).

I do not have anything else to be added before merging `develop` branch to `master` branch.

**Comment by avolkov1** [comment]
> Hi all,
> 
> I have just submitted both PR (notebook #4 and indicator_demo.ipynb).
> 
> I do not have anything else to be added before merging `develop` branch to `master` branch.

Can you list the PR #s?

**Comment by miguelangel** [comment]
We should tag before merging this 1

**Comment by miguelangel** [comment]
v0.1 release created:

https://github.com/rapidsai/gQuant/releases/tag/v0.1

**Pull request merged**
