### PR TITLE
[REVIEW] gQuant 1.0

### PR DESCRIPTION
**Pull request by yidong72**
gQuant 1.0

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by yidong72** [comment]
Updated the change log for 1.0 release

**Comment by avolkov1** [comment]
I want to test and merge #104 into develop prior to this merge to include in the 1.0 release. That #104 doesn't like version 2.6.0 of node-fetch so it wants to update it to 2.6.1.

**Comment by avolkov1** [comment]
The python environment built up in "<>/docker/build.sh" installs `dataclass` package.
```
$ conda list | grep -i dataclass
dataclasses               0.6                      pypi_0    pypi
```
This causes an error
```
'typing' has no attribute '_ClassVar'
```

Need to fix the `build.sh` script to remove the dataclass package as it is now part of the python standard library.
Fix:
```
$ pip uninstall dataclasses
```

**Comment by yidong72** [comment]
I updated the changelog to consider the merged #112

**Comment by avolkov1** [comment]
rerun tests

**Comment by yidong72** [comment]
I added a section in the README to show how to install miminum of gQuant by `pip install`

**Review by avolkov1 — CHANGES_REQUESTED** [review]
Everything looks good with regards to code, but I could not build the docker container. I had to fix two things in `build.sh` script.

Make sure to copy "README.md" because it's used by setup.py.
```
cp ../README.md ./gQuant
```

Also, looks like the latest version of jupyterlab on conda-forge is now 3.0.0. The jupyterlab stuff did not work. I had to force to version < 3.0.0
```
RUN conda install -y -c conda-forge jupyterlab'<3.0.0' 
```

With these changes I was able to build and run the container. Code wise everything looks good.

Thanks.

**Comment by yidong72** [comment]
Okay. I fixed the `build.sh` file

**Review by avolkov1 — APPROVED** [review]
Looks awesome, thanks! I'll merge this.

**Pull request merged**
