### PR TITLE
fix #26 - Add new issues template

### LINKED ISSUE #26: [FEA] Add new issue templates
Add new issue templates, similar to other RAPIDS projects.

https://github.com/rapidsai/cudf/issues/new/choose

### PR DESCRIPTION
**Pull request by miguelangel**
Fix #26 

Add new issues template, similar to:

https://github.com/rapidsai/cudf/issues/new/choose

### CODE REVIEW

**Comment by miguelangel** [comment]
Hi @yidong72,

Would it be possible to merge this change to master too?

It is risk free, and we all benefit from having it in master the sooner the better.

Regards,
Miguel

**Comment by avolkov1** [comment]
Why does this PR have a ton of files modified having nothing to do with issues template. There seems to be a lot of modifications in `notebook/cuIndicator/viz`. I don't think any files should be modified besides what goes in `.github` sub-directory.

**Comment by yidong72** [comment]
ops, I didn't pay attention to viz directory. @miguelangel, I reverted it. Please file another PR that only contains the "template" part.

**Comment by miguelangel** [comment]
Hi,

Thank you for noticing it.

My bad. ‘viz’ folder belongs to a different development I am working at (refactoring insicator_demo.ipynb notebook).

I will submit the correct PR ASAP.

Apologies again for the inconveniences.

Miguel

**Pull request merged**
