### PR TITLE
Explicit casting dataframe/series to numpy array, and fix OB indexing

### PR DESCRIPTION
**Pull request by philtrade**
Greetings! 
For `02_single_stock_trade.ipynb` to work with `bqplot` in my environment, I had to explicitly cast some dataframe slices to `numpy` array.  Also `bar_figure.axes[1]` would give out of bound index error, `s/1/0/` moved it along....

I'm on `cudf 0.14` and `bqplot 0.12.12`.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by yidong72** [comment]
we are going to test the stable 0.14 version in the next release.  currently gquant doesn't support 0.14

**Comment by philtrade** [comment]
Thanks for the heads up.

Also, just saw there is a "develop" branch.  Will there be a development branch more suitable for this PR, perhaps more align with any release schedule?

Thanks.

**Comment by yidong72** [comment]
Yes. The master branch is supposed to be a stable branch.  PRs should be based on the develop branch.  Usually, we upgrade the gQuant after the RAPIDS officially releases the new version. I am going to close this PR. You are welcome to contribute to upgrade the gQuant RAPIDS version to 0.14 once it is released.

**Comment by yidong72** [comment]
@philtrade. thanks for your suggested changes for the RAPIDS 0.14 compatibility. I create a new [PR92](https://github.com/rapidsai/gQuant/pull/92) to upgrade gQuant to RAPIDS v0.14

**Pull request closed without merging**
